# Site settings
title: MindFunc
email: hello@mindfunc.io
url: https://mindfunc.io
description: "Your Partner in Innovative Software Solutions. We excel in .NET software development and harness cutting-edge technologies like AI and machine learning. Our team delivers quality, accurate code for your business projects at affordable costs. Let us transform your ideas into reality."
keywords: ".NET, software development, AI, machine learning, quality code, affordable costs, innovative solutions, Oxfordshire, London"
skills: "Where Mind Meets Function"
meta_author:

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static
formspree_endpoint: mpzvpgqz

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 1b0641
  primary-rgb: "27,6,65"
  secondary: 1b0641
  secondary-dark: 240958

# Footer settings
footer:
  copyright: MindFunc
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: envelope fa-solid
    url: mailto:hello@mindfunc.io
  - title: linkedin fa-brands
    url: https://linkedin.com/company/mindfunc
  - title: github fa-brands
    url: https://github.com/mind-func

# Postal address (add as many lines as necessary)
address:
  - line: Oxfordshire
  - line: United Kingdom

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
