# Site settings
title: MindFunc
email: hello@mindfunc.io
url: https://mindfunc.io
description: "Your Partner in Innovative Software Solutions. We excel in .NET software development and harness cutting-edge technologies like AI and machine learning. Our team delivers quality, accurate code for your business projects at affordable costs. Let us transform your ideas into reality."
keywords: ".NET, software development, AI, machine learning, quality code, affordable costs, innovative solutions, Oxfordshire, London"
meta_author:

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static
formspree_endpoint: mpzvpgqz

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  mindfunc1: 000000
  mindfunc1-rgb: "0,0,0"
  mindfunc1: 191970
  mindfunc1-rgb: "25,25,112"
  mindfunc1: 483d8b
  mindfunc1-rgb: "72,61,139"
  mindfunc1: 4b0082
  mindfunc1-rgb: "75,0,130"
  primary: 1F0042
  primary-rgb: "31,0,66"
  secondary: 1F0042
  secondary-dark: 7246a5

# Footer settings
footer:
  copyright: MindFunc
  location: Location
  social: Keep in touch
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: envelope fa-solid
    url: mailto:hello@mindfunc.io
  - title: linkedin fa-brands
    url: https://linkedin.com/company/mindfunc
  - title: github fa-brands
    url: https://github.com/mind-func

# Postal address (add as many lines as necessary)
address:
  - line: Oxfordshire
  - line: United Kingdom

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
